version: '3.8'
services:
  db:
    image: postgres:10
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: to-do-list
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/to-do-list
